'use client';

import { useState } from 'react';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { useClinicalNotes, useCreateNote, useGenerateSOAPNote } from '@/hooks/useApi';
import { useForm } from 'react-hook-form';
import {
  Plus, X, Loader2, FileText, Sparkles, Lock, Unlock, ChevronDown, ChevronUp,
} from 'lucide-react';
import { toast } from 'sonner';
import { format } from 'date-fns';
import { cn } from '@/lib/utils';
import type { ClinicalNote } from '@/types';

const NOTE_TYPES = [
  { value: 'soap', label: 'SOAP Note', color: 'bg-blue-100 text-blue-700' },
  { value: 'progress', label: 'Progress Note', color: 'bg-green-100 text-green-700' },
  { value: 'assessment', label: 'Assessment', color: 'bg-purple-100 text-purple-700' },
  { value: 'referral', label: 'Referral', color: 'bg-orange-100 text-orange-700' },
  { value: 'discharge', label: 'Discharge', color: 'bg-slate-100 text-slate-700' },
];

export default function ClinicalNotesPage() {
  const [patientId, setPatientId] = useState('');
  const [filterPatient, setFilterPatient] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [expandedNote, setExpandedNote] = useState<string | null>(null);
  const [soapFields, setSoapFields] = useState({ s: '', o: '', a: '', p: '' });
  const [noteType, setNoteType] = useState('soap');
  const [noteTitle, setNoteTitle] = useState('');
  const [isConfidential, setIsConfidential] = useState(false);

  const { data: notesData, isLoading } = useClinicalNotes(filterPatient, { page: 1, page_size: 30 });
  const { mutateAsync: createNote, isPending: creating } = useCreateNote();
  const { mutateAsync: generateSOAP, isPending: generatingSOAP } = useGenerateSOAPNote();

  const notes = notesData?.data || [];

  const getSoapContent = () => {
    if (noteType !== 'soap') return '';
    return [
      soapFields.s ? `S: ${soapFields.s}` : '',
      soapFields.o ? `O: ${soapFields.o}` : '',
      soapFields.a ? `A: ${soapFields.a}` : '',
      soapFields.p ? `P: ${soapFields.p}` : '',
    ].filter(Boolean).join('\n\n');
  };

  const handleAIGenerate = async () => {
    if (!patientId) { toast.error('Enter a patient ID first'); return; }
    try {
      const res = await generateSOAP({ patient_id: patientId, session_context: 'latest' });
      const lines = (res.soap_note || '').split('\n');
      const newFields = { s: '', o: '', a: '', p: '' };
      lines.forEach((line: string) => {
        if (line.startsWith('S:')) newFields.s = line.replace('S:', '').trim();
        if (line.startsWith('O:')) newFields.o = line.replace('O:', '').trim();
        if (line.startsWith('A:')) newFields.a = line.replace('A:', '').trim();
        if (line.startsWith('P:')) newFields.p = line.replace('P:', '').trim();
      });
      setSoapFields(newFields);
      toast.success('SOAP note generated by AI!');
    } catch {
      toast.error('AI generation failed. Please write manually.');
    }
  };

  const handleCreate = async () => {
    const content = noteType === 'soap' ? getSoapContent() : noteTitle;
    if (!patientId || !content || !noteTitle) {
      toast.error('Please fill in all required fields');
      return;
    }
    try {
      await createNote({
        patient_id: patientId,
        note_type: noteType,
        title: noteTitle,
        content,
        is_confidential: isConfidential,
      });
      toast.success('Clinical note saved!');
      setShowForm(false);
      setNoteTitle('');
      setSoapFields({ s: '', o: '', a: '', p: '' });
      setFilterPatient(patientId);
    } catch (err: unknown) {
      toast.error((err as Error).message || 'Failed to save note');
    }
  };

  const getNoteTypeStyle = (type: string) =>
    NOTE_TYPES.find((t) => t.value === type)?.color || 'bg-slate-100 text-slate-600';

  return (
    <DashboardLayout>
      <div className="p-6 max-w-5xl mx-auto space-y-6 animate-in">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="font-display text-2xl font-bold text-slate-900">Clinical Notes</h1>
            <p className="text-slate-500 text-sm mt-1">SOAP notes, assessments, and clinical documentation</p>
          </div>
          <button
            onClick={() => setShowForm(true)}
            className="flex items-center gap-2 px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-sm font-semibold transition-colors"
          >
            <Plus className="w-4 h-4" />
            New Note
          </button>
        </div>

        {/* Filter by patient */}
        <div className="flex gap-3">
          <input
            value={filterPatient}
            onChange={(e) => setFilterPatient(e.target.value)}
            placeholder="Filter by patient ID…"
            className="flex-1 max-w-sm px-4 py-2.5 rounded-xl border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-blue-100 focus:border-blue-400"
          />
        </div>

        {/* Notes list */}
        <div className="space-y-3">
          {isLoading ? (
            <div className="flex justify-center py-16">
              <Loader2 className="w-8 h-8 animate-spin text-blue-500" />
            </div>
          ) : notes.length > 0 ? (
            notes.map((note: ClinicalNote) => {
              const expanded = expandedNote === note.id;
              return (
                <div key={note.id} className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
                  <button
                    onClick={() => setExpandedNote(expanded ? null : note.id)}
                    className="w-full flex items-center justify-between px-6 py-4 hover:bg-slate-50 transition-colors text-left"
                  >
                    <div className="flex items-center gap-3 min-w-0">
                      <span className={cn('text-xs px-2.5 py-0.5 rounded-full font-semibold flex-shrink-0', getNoteTypeStyle(note.note_type))}>
                        {NOTE_TYPES.find((t) => t.value === note.note_type)?.label || note.note_type}
                      </span>
                      <span className="font-medium text-slate-900 text-sm truncate">{note.title}</span>
                      {note.is_confidential && (
                        <Lock className="w-3.5 h-3.5 text-amber-500 flex-shrink-0" />
                      )}
                    </div>
                    <div className="flex items-center gap-3 flex-shrink-0 ml-3">
                      <span className="text-xs text-slate-400">
                        {format(new Date(note.created_at), 'MMM d, yyyy')}
                      </span>
                      {expanded
                        ? <ChevronUp className="w-4 h-4 text-slate-400" />
                        : <ChevronDown className="w-4 h-4 text-slate-400" />
                      }
                    </div>
                  </button>

                  {expanded && (
                    <div className="px-6 pb-5 border-t border-slate-50">
                      <div className="mt-4 bg-slate-50 rounded-xl p-4">
                        {note.note_type === 'soap' ? (
                          <div className="space-y-3">
                            {note.content.split('\n\n').map((section: string, i: number) => (
                              <div key={i}>
                                <p className="text-xs font-bold text-slate-600 mb-1">
                                  {section.charAt(0) === 'S' ? 'Subjective' :
                                   section.charAt(0) === 'O' ? 'Objective' :
                                   section.charAt(0) === 'A' ? 'Assessment' :
                                   section.charAt(0) === 'P' ? 'Plan' : ''}
                                </p>
                                <p className="text-sm text-slate-700 leading-relaxed">
                                  {section.replace(/^[SOAP]: /, '')}
                                </p>
                              </div>
                            ))}
                          </div>
                        ) : (
                          <p className="text-sm text-slate-700 leading-relaxed whitespace-pre-wrap">{note.content}</p>
                        )}
                      </div>
                      {note.diagnosis_codes && note.diagnosis_codes.length > 0 && (
                        <div className="flex items-center gap-2 mt-3">
                          <span className="text-xs text-slate-500">ICD Codes:</span>
                          {note.diagnosis_codes.map((code: string) => (
                            <span key={code} className="text-xs bg-blue-50 text-blue-600 px-2 py-0.5 rounded font-mono">
                              {code}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })
          ) : (
            <div className="bg-white rounded-2xl border border-slate-100 shadow-sm py-16 text-center">
              <FileText className="w-10 h-10 text-slate-200 mx-auto mb-3" />
              <p className="font-medium text-slate-600 text-sm">No clinical notes found</p>
              <p className="text-xs text-slate-400 mt-1">
                {filterPatient ? 'No notes for this patient' : 'Create your first clinical note above'}
              </p>
            </div>
          )}
        </div>

        {/* Create Note Modal */}
        {showForm && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 overflow-y-auto">
            <div className="absolute inset-0 bg-black/50" onClick={() => setShowForm(false)} />
            <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-2xl my-4">
              <div className="sticky top-0 bg-white px-6 py-5 border-b border-slate-100 flex items-center justify-between rounded-t-2xl">
                <h2 className="font-display font-bold text-lg text-slate-900">New Clinical Note</h2>
                <button onClick={() => setShowForm(false)} className="text-slate-400 hover:text-slate-700">
                  <X className="w-5 h-5" />
                </button>
              </div>

              <div className="p-6 space-y-5 overflow-y-auto max-h-[70vh]">
                {/* Patient ID */}
                <div>
                  <label className="text-sm font-medium text-slate-700 block mb-1.5">Patient ID *</label>
                  <input
                    value={patientId}
                    onChange={(e) => setPatientId(e.target.value)}
                    placeholder="Patient UUID"
                    className="w-full px-4 py-2.5 rounded-lg border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-blue-100 focus:border-blue-400"
                  />
                </div>

                {/* Note type */}
                <div>
                  <label className="text-sm font-medium text-slate-700 block mb-2">Note Type *</label>
                  <div className="flex flex-wrap gap-2">
                    {NOTE_TYPES.map((t) => (
                      <button
                        key={t.value}
                        onClick={() => setNoteType(t.value)}
                        className={cn(
                          'px-3 py-1.5 rounded-lg text-xs font-semibold border-2 transition-all',
                          noteType === t.value ? `${t.color} border-current` : 'border-slate-200 text-slate-600 hover:border-slate-300'
                        )}
                      >
                        {t.label}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Title */}
                <div>
                  <label className="text-sm font-medium text-slate-700 block mb-1.5">Note Title *</label>
                  <input
                    value={noteTitle}
                    onChange={(e) => setNoteTitle(e.target.value)}
                    placeholder="e.g. Session 5 — Post-op Assessment"
                    className="w-full px-4 py-2.5 rounded-lg border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-blue-100 focus:border-blue-400"
                  />
                </div>

                {/* SOAP fields */}
                {noteType === 'soap' ? (
                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <label className="text-sm font-semibold text-slate-700">SOAP Note</label>
                      <button
                        onClick={handleAIGenerate}
                        disabled={generatingSOAP || !patientId}
                        className="flex items-center gap-1.5 text-xs text-blue-600 hover:text-blue-700 font-medium disabled:opacity-50"
                      >
                        {generatingSOAP
                          ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
                          : <Sparkles className="w-3.5 h-3.5" />
                        }
                        AI Generate
                      </button>
                    </div>
                    {(['s', 'o', 'a', 'p'] as const).map((key) => (
                      <div key={key}>
                        <label className="text-xs font-semibold text-slate-500 uppercase tracking-wider block mb-1">
                          {key === 's' ? 'Subjective' : key === 'o' ? 'Objective' : key === 'a' ? 'Assessment' : 'Plan'}
                        </label>
                        <textarea
                          value={soapFields[key]}
                          onChange={(e) => setSoapFields((prev) => ({ ...prev, [key]: e.target.value }))}
                          placeholder={`Enter ${key === 's' ? 'patient-reported symptoms' : key === 'o' ? 'objective observations' : key === 'a' ? 'clinical assessment' : 'treatment plan'}…`}
                          rows={3}
                          className="w-full px-4 py-3 rounded-xl border border-slate-200 text-sm resize-none focus:outline-none focus:ring-2 focus:ring-blue-100 focus:border-blue-400"
                        />
                      </div>
                    ))}
                  </div>
                ) : (
                  <div>
                    <label className="text-sm font-medium text-slate-700 block mb-1.5">Content *</label>
                    <textarea
                      placeholder="Enter clinical note content…"
                      rows={6}
                      className="w-full px-4 py-3 rounded-xl border border-slate-200 text-sm resize-none focus:outline-none focus:ring-2 focus:ring-blue-100 focus:border-blue-400"
                    />
                  </div>
                )}

                {/* Confidential */}
                <div className="flex items-center gap-3">
                  <button
                    onClick={() => setIsConfidential(!isConfidential)}
                    className={cn(
                      'flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium border transition-all',
                      isConfidential
                        ? 'bg-amber-50 border-amber-200 text-amber-700'
                        : 'border-slate-200 text-slate-600 hover:border-slate-300'
                    )}
                  >
                    {isConfidential ? <Lock className="w-3.5 h-3.5" /> : <Unlock className="w-3.5 h-3.5" />}
                    {isConfidential ? 'Confidential — hidden from patient' : 'Mark as confidential'}
                  </button>
                </div>

                <button
                  onClick={handleCreate}
                  disabled={creating}
                  className="w-full py-3 rounded-xl dynax-gradient text-white font-semibold text-sm hover:opacity-90 transition-opacity disabled:opacity-60 flex items-center justify-center gap-2"
                >
                  {creating && <Loader2 className="w-4 h-4 animate-spin" />}
                  Save Clinical Note
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
